FROM node as node

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2
FROM nginx:alpine
COPY --from=node /usr/src/app/dist/cp-sms-frontend /usr/share/nginx/html
COPY Docker.nginx.default.conf /etc/nginx/conf.d/default.conf