# Stage 1
FROM node as node

WORKDIR /src/app

COPY . .

# Need to build project before rund docker build...
#
# RUN npm install
# 
# RUN npm run build

# Stage 2
FROM nginx:alpine

COPY --from=node /src/app/dist/cp-trip-sharing-frontend /share/nginx/html

COPY nginx.default.conf /etc/nginx/conf.d/default.conf